---
apiVersion: v1
kind: Service
metadata:
  name: first-node-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
  selector:
     tag: free
---
