---
apiVersion: v1
kind: Pod
metadata:
  name: trial-pod
  labels:
    tag: mee
spec:
  containers:
    - name: httpd2
      image: httpd
      ports:
        - containerPort: 80
          name: mee-port
---

